# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your actual API key

[default]
GEMINI_API_KEY = "AIzaSyDJpS-vOpOQXdsWQG5iKunReCHqG4OZdOg"

# Get your free API key from: https://ai.google.dev/
# Then replace the placeholder above with your actual key
