GEMINI_API_KEY = "AIzaSyDJpS-vOpOQXdsWQG5iKunReCHqG4OZdOg"
[google_oauth]
CLIENT_ID = "700087416013-8r47qlsjf7vspevr4k43ki56qn2s7mjh.apps.googleusercontent.com"
CLIENT_SECRET = "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"
REDIRECT_URI = "http://localhost:8501"  # 開發時可用；部署後改成你的公開網址